### PR TITLE
[WIP] Unit testing

### PR DESCRIPTION
**Pull request by vanadium23**
Hello, gi0baro.

I see your wanted help in testing from issue #3. And start working on some unit test.

Do you have any suggestions on what focus first?
Also testing found some bug in SessionCookieManager, and I'll fix it soon.

Thanks in advance for answer. (:

### CODE REVIEW

**Comment by gi0baro** [comment]
@vanadium23 That's huge man, thank you! I see that you added a MakeFile, that's nice!
You've added coveralls too, and even if I'm not a *big fan*, we can try use it; I'm not so "confident" about its results, also because it's not so smart to understand that sometimes there's no need to test some lines. Do you think we should use it?

Regarding your question, apart for what you've added, I think the router (expose module) should be one of the first to focus on.

**Comment by vanadium23** [comment]
I agree, that there is no reason to have 100% coverage, because clean code is impossible. But many good products using tests (and test coverage) for stabilizing api/contracts. I have

**Comment by vanadium23** [comment]
I agree, that there is no reason to have 100% coverage, because clean code is impossible. But many good products using tests (and test coverage) for stabilizing api/contracts. (So if you change something, you'll see directly from build result).

_May be I'm too concerned about number, but I'd love to see 90% coverage badge at repos (:_

**Comment by gi0baro** [comment]
@vanadium23 ok, let's add coveralls :) let me know when I can merge this.

**Comment by vanadium23** [comment]
I think I'm done for now. May be later I'll add more tests, but want to do it in separate request after try more features from weppy.

**Comment by gi0baro** [comment]
@vanadium23 Thank you :)

**Pull request merged**
