### PR TITLE
Debug, response, app and module, README review

### PR DESCRIPTION
**Pull request by lethargilistic**

### CODE REVIEW

**Comment by gi0baro** [comment]
@lethargilistic I'm reviewing the changes and seems that markdown is not really happy with the 80 characters length thing. Seems to brake tables, change the paragraphs structure in un-predictable ways.. I'm afraid we need to revert the 80 lines thing.

**Comment by lethargilistic** [comment]
Oh, shoot. I'm sorry. I'll fix it.

**Comment by lethargilistic** [comment]
I've fixed the tables. Can you point me to where the paragraph structure broke, so I'll know when I've fixed it?

**Comment by gi0baro** [comment]
@lethargilistic I've noticed just in the foreword right now, in the paragraph: 

I really enjoyed writing code in Python, and after gaining some confidence,
I faced the second "big decision"...

**Pull request merged**
